INSERT INTO REVIEWS (Title, Comment, Rating, GameID, UserID) VALUES
("FIFA 23: Il miglior FIFA", "FIFA 23 offre un’esperienza calcistica migliorata con animazioni più fluide e un’intelligenza artificiale più raffinata. La parte online è stabile, ma la modalità carriera potrebbe essere più profonda.", 4.7, 78, 1),
("Ottimo, ma migliorabile", "FIFA 23 è un passo avanti rispetto al passato, con un miglioramento nelle meccaniche di gioco e nelle animazioni. Tuttavia, la modalità carriera può ancora migliorare in termini di profondità e personalizzazione.", 4.6, 78, 10),
("Molto divertente ma con margini di miglioramento", "FIFA 23 è un gioco eccellente, ma la parte online continua a non essere stabile al 100%. Le animazioni sono ottime, ma la modalità carriera necessita di maggiore varietà.", 4.5, 78, 20),
("FIFA 23 è il solito FIFA", "FIFA 23 porta piccoli miglioramenti, ma la formula è sempre la stessa. La parte online funziona bene, ma la modalità carriera ha ancora margini di miglioramento.", 4.4, 78, 30),
("Ottimi miglioramenti ma manca innovazione", "FIFA 23 ha migliorato il gameplay, ma non ci sono cambiamenti radicali. La modalità carriera è ancora interessante, ma avrebbe potuto essere più innovativa.", 4.5, 78, 40),
("FIFA 23: Ottimo gameplay, ma non rivoluzionario", "FIFA 23 è un buon gioco con ottimi miglioramenti nel gameplay e nella grafica, ma non riesce a fare un salto evolutivo significativo rispetto ai capitoli precedenti.", 4.6, 78, 50),
("Poca innovazione", "FIFA 23 è molto simile ai precedenti capitoli. La grafica è migliorata, ma manca quel “wow” che ci si aspettava da un nuovo capitolo della serie. La parte online è buona, ma la carriera è rimasta stagnante.", 4.3, 78, 60),
("FIFA 23 è un buon gioco", "FIFA 23 è un buon gioco calcistico, ma non riesce a fare il salto di qualità che molti si aspettavano. La parte online è stabile, ma la modalità carriera rimane troppo simile ai precedenti capitoli.", 4.4, 78, 70),
("Divertente ma privo di novità", "FIFA 23 è divertente come sempre, ma non offre particolari innovazioni rispetto al passato. La parte online funziona bene, ma la carriera può essere migliorata.", 4.5, 78, 80),
("Un buon FIFA, ma non il migliore", "FIFA 23 è sicuramente uno dei migliori capitoli della serie, ma manca quella spinta innovativa che avrebbe dovuto fare la differenza. Comunque, resta un gioco calcistico di qualità.", 4.5, 78, 90);

INSERT INTO REVIEWS (Title, Comment, Rating, GameID, UserID) VALUES
("Final Fantasy VII Remake: Un capolavoro", "Final Fantasy VII Remake è un gioco eccezionale con una trama coinvolgente, grafica mozzafiato e un sistema di combattimento fantastico. Un must per i fan del gioco originale!", 5.0, 27, 1),
("Una rivisitazione fantastica", "FFVII Remake riporta alla luce la magia del gioco originale con una grafica sorprendente e un gameplay aggiornato. La storia è ancora incredibile, ma avrei voluto vedere più parti del gioco originale.", 4.8, 27, 10),
("Un remake che vale la pena", "Final Fantasy VII Remake ha aggiornato il classico con una nuova esperienza più dinamica e moderna. Nonostante alcune scelte di trama discutibili, è un gioco che i fan apprezzeranno sicuramente.", 4.7, 27, 20),
("Final Fantasy VII Remake: Imperdibile per i fan", "FFVII Remake è il miglior remake che potessero fare. Con una trama avvincente e un combattimento spettacolare, è un gioco che ogni fan della serie deve giocare.", 4.9, 27, 30),
("Un’avventura emozionante", "La grafica e il gameplay di FFVII Remake sono semplicemente fantastici, ma mi sarebbe piaciuto che avessero mantenuto un po’ di più dello stile originale. La trama è comunque epica e coinvolgente.", 4.8, 27, 40),
("Un grande remake", "FFVII Remake riesce a mantenere la magia dell’originale, pur aggiornando il gioco per le nuove generazioni. Non è perfetto, ma è sicuramente un’esperienza che vale la pena vivere.", 4.7, 27, 50),
("Bellissimo, ma incompleto", "Final Fantasy VII Remake è uno dei giochi più belli che abbia mai giocato, ma mi ha lasciato con la sensazione di non aver vissuto tutta la storia. Aspetto con ansia il seguito!", 4.6, 27, 60),
("Un remake che supera le aspettative", "Final Fantasy VII Remake è un gioco stupendo che riesce a catturare l’essenza del titolo originale, pur portando alcune novità interessanti. Non vedo l’ora di giocare al prossimo capitolo!", 4.9, 27, 70),
("Un capolavoro moderno", "La qualità grafica, la musica e la storia sono semplicemente incredibili in FFVII Remake. Un gioco che farà battere il cuore di ogni appassionato di RPG e di Final Fantasy.", 5.0, 27, 80),
("Final Fantasy VII Remake: La nuova era", "FFVII Remake è il remake perfetto: bello, emozionante, e completamente coinvolgente. Un’avventura che consiglio a tutti, anche a chi non ha mai giocato al gioco originale.", 4.9, 27, 90);

INSERT INTO REVIEWS (Title, Comment, Rating, GameID, UserID) VALUES
("Final Fantasy XIV: Il miglior MMORPG", "FFXIV è senza dubbio il miglior MMORPG in circolazione. Con una storia coinvolgente, un sistema di gioco ben bilanciato e un supporto continuo da parte degli sviluppatori, è il gioco perfetto per chi ama il genere.", 5.0, 122, 1),
("Un MMORPG che non delude", "Final Fantasy XIV è un gioco che continua a migliorare. Con nuove espansioni e continui aggiornamenti, offre una delle esperienze di gioco online più complete e divertenti.", 4.9, 122, 10),
("Un MMORPG da non perdere", "FFXIV è il MMORPG che ogni appassionato del genere dovrebbe provare. La storia è fantastica e le modalità di gioco sono varie, ma richiede un po’ di tempo per essere pienamente apprezzato.", 4.8, 122, 20),
("Final Fantasy XIV è un sogno per i fan dei MMORPG", "Con una storia epica e una comunità incredibile, FFXIV è il miglior MMORPG che esista. Le espansioni aggiungono tantissimo e continuano a mantenere il gioco fresco e interessante.", 5.0, 122, 30),
("Un’esperienza unica", "Final Fantasy XIV è il miglior gioco MMORPG al momento. La trama è fantastica, le espansioni sono grandiose, e la grafica è spettacolare. La curva di apprendimento è un po’ ripida, ma ne vale la pena.", 4.7, 122, 40),
("FFXIV: Un gioco che ti conquista", "FFXIV ti cattura fin dal primo momento. La storia, la grafica e il gameplay sono fantastici. È uno dei giochi più coinvolgenti che abbia mai giocato, e continuo a giocarlo da anni.", 4.9, 122, 50),
("Il miglior MMORPG che ci sia", "Final Fantasy XIV è il gioco perfetto per chi ama i MMORPG. La comunità è fantastica, la storia è coinvolgente e ci sono tantissime cose da fare. Se ami il genere, devi provarlo.", 5.0, 122, 60),
("Incredibile, ma complesso", "FFXIV è un MMORPG magnifico, ma la curva di apprendimento può essere difficile all’inizio. Nonostante questo, una volta che entri nel gioco, non vorrai più smettere di giocare.", 4.8, 122, 70),
("Una gemma da scoprire", "Final Fantasy XIV è un gioco incredibile che continua a crescere. Se ami gli MMORPG, non puoi perderlo. Ha tantissime espansioni e una storia che ti terrà incollato al monitor per ore.", 4.9, 122, 80),
("Final Fantasy XIV: Il capolavoro del MMORPG", "FFXIV è il miglior MMORPG mai creato. Con un mondo ricco di dettagli, una trama emozionante e una comunità che rende il gioco ancora più speciale, è un’esperienza che consiglio a tutti.", 5.0, 122, 90);

INSERT INTO REVIEWS (Title, Comment, Rating, GameID, UserID) VALUES
("Final Fantasy XV: Un viaggio emozionante", "Final Fantasy XV offre un mondo aperto incredibile e un sistema di combattimento dinamico. Nonostante alcune scelte di trama discutibili, è un gioco che vale assolutamente la pena giocare.", 4.7, 59, 1),
("Una grande avventura", "FFXV è un’avventura epica che riesce a catturare il cuore del giocatore. La trama è coinvolgente e la grafica è spettacolare. Tuttavia, la parte finale potrebbe essere migliorata.", 4.8, 59, 10),
("Un gioco magnifico, ma con qualche difetto", "FFXV ha una storia incredibile e un gameplay entusiasmante, ma soffre di alcuni difetti nel ritmo e nelle missioni secondarie. Il finale è un po’ troppo affrettato.", 4.6, 59, 20),
("Un viaggio indimenticabile", "La storia di FFXV è emozionante e i personaggi sono molto ben sviluppati. Nonostante alcune pecche nel gameplay, il gioco riesce comunque a far vivere un’esperienza unica.", 4.7, 59, 30),
("Final Fantasy XV: La fine di un’era", "FFXV segna la fine di una saga, e lo fa con stile. Il mondo di gioco è vasto e ricco di contenuti, ma alcune scelte narrative non sono all’altezza delle aspettative.", 4.5, 59, 40),
("Un’esperienza molto divertente", "Nonostante i suoi difetti, FFXV è un gioco che non delude. La grafica è fantastica e il gameplay è divertente. I personaggi sono ben scritti e la storia è coinvolgente.", 4.6, 59, 50),
("Molto bello, ma non perfetto", "FFXV è un gioco che offre molte ore di intrattenimento. La trama è buona, ma avrebbe potuto essere più coesa. Nonostante questo, è sicuramente un gioco che consiglio a tutti.", 4.6, 59, 60),
("Storia emozionante, ma gameplay migliorabile", "FFXV ha una delle storie più emozionanti della saga di Final Fantasy, ma il gameplay è meno interessante rispetto ad altri capitoli della serie. La libertà offerta dal mondo aperto è fantastica.", 4.5, 59, 70),
("FFXV: Un gioco da provare", "Final Fantasy XV offre un’avventura coinvolgente, ma presenta anche alcuni problemi nel ritmo e nella gestione della trama. Non è perfetto, ma ha comunque molto da offrire.", 4.7, 59, 80),
("Final Fantasy XV: Il sogno di Noctis", "FFXV è un gioco che non ti lascia mai annoiare. Il mondo è grande e ricco di segreti, ma alcune missioni secondarie possono risultare ripetitive. Comunque, è un titolo che ogni fan dovrebbe giocare.", 4.8, 59, 90);

INSERT INTO REVIEWS (Title, Comment, Rating, GameID, UserID) VALUES
("Final Fantasy XVI: Un capolavoro", "Final Fantasy XVI è un capolavoro visivo e narrativo. La storia è coinvolgente, i combattimenti sono dinamici e il mondo di gioco è spettacolare. Un gioco da non perdere!", 5.0, 26, 1),
("Un’esperienza fantastica", "FFXVI ha una trama fantastica e un gameplay che ti tiene incollato allo schermo. La grafica è incredibile, ma la parte RPG potrebbe essere più profonda. Comunque, è un gioco che vale assolutamente la pena giocare.", 4.8, 26, 10),
("Un altro grande capitolo", "FFXVI è un ottimo capitolo della serie. La storia è coinvolgente e i combattimenti sono estremamente dinamici, ma la personalizzazione dei personaggi potrebbe essere migliorata.", 4.7, 26, 20),
("Final Fantasy XVI: Non delude", "FFXVI è un gioco che non delude le aspettative. La grafica è incredibile, la storia è emozionante, ma a volte il gameplay può sembrare troppo lineare. Comunque, è un must per i fan della serie.", 4.9, 26, 30),
("Un’esperienza indimenticabile", "FFXVI è il migliore capitolo della saga da anni. La trama è profonda, i combattimenti sono fluidi, ma la parte RPG è un po’ più leggera rispetto ai giochi precedenti.", 4.8, 26, 40),
("Un grande gioco, ma con qualche difetto", "Final Fantasy XVI è un gioco spettacolare con una trama che ti tiene incollato. Tuttavia, mi sarebbe piaciuto avere più opzioni di personalizzazione e una maggiore libertà nelle decisioni.", 4.7, 26, 50),
("Molto bello, ma non perfetto", "FFXVI è un gioco stupendo dal punto di vista grafico e narrativo. Tuttavia, alcuni aspetti del gameplay possono sembrare ripetitivi e la personalizzazione è limitata.", 4.6, 26, 60),
("Final Fantasy XVI: Una nuova era", "FFXVI segna un nuovo capitolo per la saga, con una trama più matura e una grafica spettacolare. Nonostante ciò, alcuni fan potrebbero sentirsi disorientati dal cambiamento del gameplay.", 4.7, 26, 70),
("FFXVI è spettacolare", "Final Fantasy XVI è un gioco che merita tutta la fama che ha ricevuto. La storia è incredibile e i combattimenti sono divertenti, ma la gestione delle missioni secondarie potrebbe essere migliore.", 4.8, 26, 80),
("Un gioco che non delude", "Final Fantasy XVI è uno dei migliori giochi di ruolo degli ultimi anni. La trama è coinvolgente, i personaggi sono ben sviluppati e i combattimenti sono incredibili. Non vedo l’ora di vedere cosa succederà nei prossimi capitoli.", 4.9, 26, 90);


INSERT INTO REVIEWS (Title, Comment, Rating, GameID, UserID) VALUES
("Fire Emblem: Three Houses: Una strategia eccezionale", "Fire Emblem: Three Houses è un capolavoro della strategia. La trama è profonda, le scelte sono significative e il gameplay è molto coinvolgente. Un must per ogni fan della serie!", 5.0, 183, 1),
("Un gioco strategico da non perdere", "Three Houses offre una combinazione perfetta di combattimento tattico e narrazione. Le scelte che fai influenzano davvero la storia, e questo lo rende un gioco che si può giocare più volte senza annoiarsi.", 4.9, 183, 10),
("Fire Emblem: Three Houses è fantastico", "La profondità del gameplay e la varietà di scelte narrative lo rendono uno dei migliori giochi di strategia. Tuttavia, alcune missioni possono sembrare ripetitive.", 4.8, 183, 20),
("Un capolavoro tattico", "Fire Emblem: Three Houses ha una trama incredibile e un sistema di combattimento strategico che ti tiene impegnato per ore. Le decisioni che prendi durante il gioco sono fondamentali, e ogni percorso offre nuove sorprese.", 5.0, 183, 30),
("Una delle migliori esperienze strategiche", "Three Houses è uno dei migliori giochi di strategia che abbia mai giocato. Le sue meccaniche sono profonde e le opzioni di personalizzazione sono enormi. Un gioco che ogni appassionato di RPG e tattica dovrebbe giocare.", 4.9, 183, 40),
("Molto divertente, ma con margini di miglioramento", "Il gameplay di Three Houses è fantastico, ma alcuni livelli di difficoltà possono sembrare troppo facili, soprattutto dopo aver acquisito familiarità con le meccaniche del gioco.", 4.7, 183, 50),
("Un gioco incredibile", "Three Houses è una combinazione perfetta di strategia e storytelling. Ogni scelta che fai ha un impatto sulla storia, e le diverse case offrono esperienze completamente diverse.", 5.0, 183, 60),
("Un gioco fantastico ma impegnativo", "Three Houses è un gioco che richiede pazienza e strategia. La storia è emozionante, ma il gameplay può risultare difficile da padroneggiare all’inizio. Un must per gli amanti della strategia.", 4.8, 183, 70),
("Fire Emblem: Three Houses è fenomenale", "Questo gioco è un must per chi ama la strategia. Ogni scelta nella storia sembra pesare, e le battaglie sono sempre coinvolgenti. Non vedo l’ora di giocare alla prossima versione!", 4.9, 183, 80),
("Un’esperienza unica nel suo genere", "Three Houses offre una trama ricca di scelte e conseguenze. Il gameplay tattico è profondo e gratificante, e ogni personaggio ha una propria storia interessante.", 4.9, 183, 90);

INSERT INTO REVIEWS (Title, Comment, Rating, GameID, UserID) VALUES
("Fire Emblem: Warriors: Un ottimo spin-off", "Fire Emblem: Warriors è un gioco d’azione che mescola la strategia della saga principale con combattimenti frenetici. Ottimo per chi ama il combattimento in stile musou, ma perde parte della profondità della serie principale.", 4.3, 40, 1),
("Un gioco d’azione divertente", "Nonostante Fire Emblem: Warriors non abbia la stessa profondità strategica dei titoli principali della serie, è comunque un gioco molto divertente con un buon numero di personaggi e missioni.", 4.5, 40, 10),
("Molto divertente, ma ripetitivo", "Il gioco è divertente e pieno di azione, ma a lungo andare le missioni possono diventare un po’ ripetitive. Comunque, i fan di Fire Emblem e dei giochi musou troveranno molto da apprezzare.", 4.2, 40, 20),
("Un buon spin-off", "Fire Emblem: Warriors è un buon spin-off, ma manca della profondità che rende unica la serie principale. Tuttavia, i combattimenti sono spettacolari e i fan dei musou si divertono sicuramente.", 4.4, 40, 30),
("Un’esperienza divertente, ma poco profonda", "Il gameplay di Fire Emblem: Warriors è molto divertente, ma non offre la stessa complessità strategica di altri titoli della saga. Se ti piacciono i giochi d’azione veloci, vale la pena provarlo.", 4.3, 40, 40),
("Divertente, ma non per tutti", "Fire Emblem: Warriors è divertente per i fan delle battaglie veloci e dell’azione, ma se cerchi la profondità tipica dei giochi di strategia, questo non fa per te.", 4.1, 40, 50);

INSERT INTO REVIEWS (Title, Comment, Rating, GameID, UserID) VALUES
("For the King: Un gioco di strategia e cooperazione", "For the King è un gioco di ruolo strategico che richiede cooperazione tra i giocatori. La difficoltà aumenta gradualmente e la varietà di scelte rende ogni partita unica.", 4.6, 51, 1),
("Un gioco cooperativo fantastico", "La combinazione di esplorazione, combattimento a turni e strategia rende For the King un’esperienza avvincente. La cooperazione tra i giocatori è fondamentale per avere successo.", 4.7, 51, 10),
("Strategico ma frustrante", "For the King è un gioco molto strategico, ma alcune meccaniche possono risultare frustranti, soprattutto nelle partite in solitario. La cooperazione è davvero importante per godere appieno del gioco.", 4.4, 51, 20),
("Un bel gioco di strategia", "For the King è un gioco che sfida il giocatore a prendere decisioni difficili in un mondo generato proceduralmente. Le meccaniche di gioco sono solide e offre molte ore di divertimento.", 4.6, 51, 30),
("Un gioco di ruolo solido", "For the King è un gioco di ruolo che ti permette di esplorare un mondo ricco di pericoli e sfide. La modalità cooperativa aggiunge una dimensione in più al gioco, ma a volte può essere difficile da gestire.", 4.5, 51, 40),
("Più difficile di quanto sembri", "For the King è un gioco di strategia che ti mette alla prova. Ogni partita è diversa, ma la difficoltà è spesso elevata, specialmente quando si gioca in solitaria.", 4.3, 51, 50);

INSERT INTO REVIEWS (Title, Comment, Rating, GameID, UserID) VALUES
("Forza Horizon 4: La migliore esperienza di guida", "Forza Horizon 4 è un capolavoro di gioco di corse. Il mondo aperto è vasto e bellissimo, le auto sono fantastiche e il sistema di progressione è coinvolgente. È il miglior gioco di corse degli ultimi anni.", 5.0, 234, 1),
("Un gioco da sogno per gli appassionati di corse", "Forza Horizon 4 è semplicemente incredibile. La grafica è mozzafiato e il gameplay è impeccabile. Non c’è niente di meglio di correre per le strade della Gran Bretagna in una Ferrari.", 4.9, 234, 10),
("Il miglior gioco di corse open-world", "Forza Horizon 4 offre un mondo aperto stupendo da esplorare e un gameplay di guida che è sia divertente che realista. La varietà di auto e eventi è impressionante.", 4.8, 234, 20),
("Un gioco che non delude mai", "Forza Horizon 4 è il miglior gioco di corse open-world che abbia mai giocato. Ogni gara è emozionante e la personalizzazione delle auto è molto profonda. Un must per ogni amante delle corse.", 5.0, 234, 30),
("Stupendo, ma con piccoli difetti", "Forza Horizon 4 è incredibile, ma la difficoltà nelle gare può variare troppo, rendendo alcune esperienze frustranti. Nonostante questo, il gioco è ancora fantastico.", 4.7, 234, 40),
("Il miglior gioco di guida di sempre", "Forza Horizon 4 è il gioco di guida definitivo. La libertà di esplorare il mondo è eccezionale, e le gare sono sempre divertenti. I difetti sono minimi rispetto alla qualità complessiva del gioco.", 4.9, 234, 50);

INSERT INTO REVIEWS (Title, Comment, Rating, GameID, UserID) VALUES
("Forza Horizon 5: Il miglior gioco di corse open-world", "Forza Horizon 5 è un gioco che definisce nuovi standard per i giochi di corse open-world. La grafica è incredibile, l’ambiente è ricco di dettagli e le corse sono sempre emozionanti.", 5.0, 81, 1),
("Un capolavoro della serie", "Forza Horizon 5 porta la serie a nuovi livelli. La varietà di auto e la vastità dell’ambiente open-world in Messico è fenomenale. Un gioco che non delude mai.", 4.9, 81, 10),
("Vibrante e spettacolare", "Il paesaggio messicano in Forza Horizon 5 è spettacolare, con ogni gara che ti fa sentire parte del mondo. È un’esperienza di guida che ti fa sognare.", 4.8, 81, 20),
("Il miglior gioco di corse mai creato", "Forza Horizon 5 è un gioco incredibile. La grafica, la varietà di eventi e la sensazione di guida sono senza pari. È un gioco che ti tiene impegnato per ore.", 5.0, 81, 30),
("Una corsa emozionante", "Forza Horizon 5 offre emozioni pure. Ogni corsa è diversa e offre nuove sfide, con una varietà di modalità che tengono sempre alta l’attenzione.", 4.7, 81, 40),
("Pura adrenalina", "La combinazione di grafica mozzafiato e gameplay coinvolgente rende Forza Horizon 5 un gioco straordinario. Le gare sono sempre intense, e l’esplorazione è entusiasmante.", 4.8, 81, 50),
("Perfetto per gli amanti delle corse", "Se ami i giochi di corse, Forza Horizon 5 è un must. La personalizzazione delle auto, il mondo aperto e la varietà di gare ti tengono incollato allo schermo per ore.", 4.9, 81, 60),
("Un’esperienza unica", "Forza Horizon 5 ti offre una sensazione di libertà unica grazie al suo vasto mondo aperto e alle tante modalità di gioco. Ogni corsa è un’avventura.", 4.7, 81, 70),
("Eccezionale sotto ogni punto di vista", "Forza Horizon 5 è eccezionale in tutti gli aspetti. La grafica, la varietà di contenuti, il gameplay fluido e la sensazione di velocità sono tutti perfetti. Un gioco che ogni appassionato di corse dovrebbe provare.", 5.0, 81, 80),
("Un capolavoro del racing", "Forza Horizon 5 è semplicemente un capolavoro. Non c’è niente di più divertente che sfrecciare attraverso il paesaggio messicano, con un’auto perfettamente personalizzata. Un gioco che ti fa tornare per una corsa dopo l’altra.", 4.9, 81, 90);